### PR TITLE
Version 2.0.0

### PR DESCRIPTION
**Pull request by yen-tt**
### Breaking Changes
- Re-exported all modified and newly added direct answer related interfaces from search-core V2. (#131 #133 #136 ) 
  - More details of the changes are listed in [search-core v2 release notes](https://github.com/yext/search-core/releases/tag/v2.0.0)
- Restructured static filters state to allow user to store more complex combination of static filters as well as field value filters. `SelectableFilter` interface is replaced with `SelectableStaticFilter`, which uses the new `StaticFilter` interface from search-core V2. The static filters state now accepts an array of `SelectableStaticFilter`. (#130 )
- All exports marked as `@deprecated` in previous version(s) as part of a rebranding process is now removed in V2 (#132  )
  - for more details, the removed deprecated identifiers are listed in [v1.3 release notes](https://github.com/yext/search-headless/releases/tag/v1.3.0)

### CODE REVIEW

**Comment by yen-tt** [comment]
will update headless and core version to 2.0.0 once core version v2 is released.

**Review by oshi97 — APPROVED** [review]

**Review by oshi97 — APPROVED** [review]

**Comment by nmanu1** [comment]
should the DA stuff also go under breaking changes? I think if people are extending the existing models, their stuff would break with the changes

**Comment by yen-tt** [comment]
> should the DA stuff also go under breaking changes? I think if people are extending the existing models, their stuff would break with the changes

updated description! Also linked to search-core v2 for more info of the changes

**Comment by nmanu1** [comment]
> re-exported all modified and newly

nit: capital r at the beginning to be consistent

**Review by nmanu1 — APPROVED** [review]

**Pull request merged**
