### PR TITLE
v1.3.0

### PR DESCRIPTION
**Pull request by ElemelonWind**
## Version 1.3.0
`@yext/answers-headless` is now `@yext/search-headless`!  This means that much of the `answers` terminology is now deprecated and have been replaced by new `search` terms.
### Changes
- The following identifiers were renamed in (https://github.com/yext/search-headless/pull/116):
  - `answersUtilities` &rarr; `searchUtilities`
  - `provideAnswersHeadless` &rarr; `provideHeadless`
  - `AnswersHeadless` &rarr; `SearchHeadless`
- Additionally, direct exports from what was previously `@yext/answers-core` have been replaced by their `@yext/search-core` counterparts:
   - `AnswersConfig` &rarr; `SearchConfig`
   - `AnswersConfigWithToken` &rarr; `SearchConfigWithToken`
   - `AnswersConfigWithApiKey` &rarr; `SearchConfigWithApiKey`
   - `AnswersCore` &rarr; `SearchCore`
   - `AnswersError` &rarr; `SearchError`
   - `AnswersRequest` &rarr; `SearchRequest`
   - `BaseAnswersConfig` &rarr; `BaseSearchConfig`

### CODE REVIEW

**Comment by oshi97** [comment]
Could you type up some release notes? Can look at alex's for search-core or other past ones for reference but also feel free to write them your own way! Then the release notes will be the PR description here

**Comment by ElemelonWind** [comment]
> Could you type up some release notes? Can look at alex's for search-core or other past ones for reference but also feel free to write them your own way! Then the release notes will be the PR description here

done :) can you look over it?

**Review by nmanu1 — COMMENTED** [review]
can you also update the PR name and the name of the commit to something like `Version 1.3.0` or `v1.3.0` when you merge it in?

**Comment by ElemelonWind** [comment]
> can you also update the PR name and the name of the commit when you merge it in (e.g. something like `Version 1.3.0` or `v1.3.0` )?

How do you change the name of the commit lol

**Comment by nmanu1** [comment]
> How do you change the name of the commit lol

I meant when you're going to merge it into `main`, you should set the name of the commit and the commit message to match the PR title and description, respectively

**Review by oshi97 — APPROVED** [review]

**Pull request merged**
