### PR TITLE
Answers -> Search renaming

### PR DESCRIPTION
**Pull request by ElemelonWind**
J=SLAP-2204
TEST=auto

### CODE REVIEW

**Comment by oshi97** [comment]
Could we have a PR to update variable names and test fixture names? If that's going to be a separate thing lgtm!

**Comment by ElemelonWind** [comment]
> Could we have a PR to update variable names and test fixture names? If that's going to be a separate thing lgtm!

Yeah I just confirmed with Tom yesterday, internal stuff is going to be another phase of the renaming :)

**Review by nmanu1 — COMMENTED** [review]
this should be merged into `develop` instead of `main`

**Comment by ElemelonWind** [comment]
> this should be merged into `develop` instead of `main`

Is the npm package going to be from `develop`?

**Comment by nmanu1** [comment]
> Is the npm package going to be from `develop`?

we would merge into `develop`, and then make a `release` branch to merge into `main`, like Alex did for Core. then we'd publish to NPM from `main`

**Review by oshi97 — APPROVED** [review]

**Comment by ElemelonWind** [comment]
> > Is the npm package going to be from `develop`?
> 
> we would merge into `develop`, and then make a `release` branch to merge into `main`, like Alex did for Core. then we'd publish to NPM from `main`

aah got it ty!

**Pull request merged**
